from collections import defaultdict

feature_config = dict(
    faisalabad=['age', 'anaemia', 'creatinine_phosphokinase', 'diabetes',
                'ejection_fraction', 'high_blood_pressure', 'platelets',
                'serum_creatinine', 'serum_sodium', 'sex', 'smoking'],
    unos=["init_age", "gender", "hgt_cm_tcr", "wgt_kg_tcr", "diab", "ventilator_tcr",
          "ecmo_tcr", "most_rcnt_creat", "abo_A", "abo_B", "abo_O", "vad_while_listed",
          "iabp_tcr", "init_bmi_calc", "tah", "inotropic"],
    flchain=['flc.grp', 'creatinine', 'kappa', 'sample.yr', 'lambda', 'age', 'sex', 'mgus'],
    gbsg=['x4', 'x5', 'x0', 'x1', 'x6', 'x2', 'x3'],
    metabric=['x7', 'x4', 'x8', 'x5', 'x0', 'x1', 'x6', 'x2', 'x3'],
    nwtco=['histol_2', 'instit_2', 'study_4', 'age', 'in.subcohort', 'stage'],
    ist=["RDELAY","RCONSC","SEX","AGE","RSLEEP","RATRIAL","RCT","RVISINF","RHEP24",
         "RASP3","RSBP","RDEF1","RDEF2","RDEF3","RDEF4","RDEF5","RDEF6","RDEF7","RDEF8","STYPE"]
)

clinical_feature_type = dict(
    faisalabad={
        'age': 'numerical',
        'anaemia': 'categorical',
        'creatinine_phosphokinase': 'numerical',
        'diabetes': 'categorical',
        'ejection_fraction': 'numerical',
        'high_blood_pressure': 'categorical',
        'platelets': 'numerical',
        'serum_creatinine': 'numerical',
        'serum_sodium': 'numerical',
        'sex': 'categorical',
        'smoking': 'categorical',
    },
    unos={'init_age': 'numerical',
          'gender': 'categorical',
          'hgt_cm_tcr': 'numerical',
          'wgt_kg_tcr': 'numerical',
          'diab': 'categorical',
          'ventilator_tcr': 'categorical',
          'ecmo_tcr': 'categorical',
          'most_rcnt_creat': 'numerical',
          'abo_A': 'categorical',
          'abo_B': 'categorical',
          'abo_O': 'categorical',
          'vad_while_listed': 'categorical',
          'days_stat1': 'numerical',
          'days_stat1a': 'numerical',
          'days_stat2': 'numerical',
          'days_stat1b': 'numerical',
          'iabp_tcr': 'categorical',
          'init_bmi_calc': 'numerical',
          'tah': 'categorical',
          'inotropic': 'categorical'},
    flchain={'flc.grp': 'categorical', 
             'creatinine': 'numerical', 
             'kappa': 'numerical', 
             'sample.yr': 'categorical', 
             'lambda': 'numerical',
             'age': 'numerical',
             'sex': 'categorical',
             'mgus': 'categorical'},
    gbsg={'x4': 'numerical',
          'x5': 'numerical', 
          'x0':'categorical', 
          'x1':'categorical', 
          'x6': 'numerical', 
          'x2':'categorical', 
          'x3': 'numerical'},
    metabric={'x7':'categorical', 
              'x4':'categorical', 
              'x8': 'numerical', 
              'x5':'categorical', 
              'x0': 'numerical', 
              'x1': 'numerical', 
              'x6':'categorical', 
              'x2': 'numerical', 
              'x3': 'numerical'},
    nwtco={'histol_2': 'categorical', 
           'instit_2': 'categorical', 
           'study_4': 'categorical', 
           'age': 'numerical', 
           'in.subcohort': 'categorical', 
           'stage': 'categorical'}
)

feature_transforms = defaultdict(lambda: defaultdict(list))

for dataset_name, feature_dict in clinical_feature_type.items():
    for feature_name, feature_type in feature_dict.items():
        feature_transforms[dataset_name][feature_type].append(feature_name)
